version: '2'
services:
  web:
    build: .
    ports:
      - "80:8888"
    depends_on:
      - redis-master
      - redis-slave

  redis-master:
    image: gcr.io/google_containers/redis:e2e

  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1

  influxdb:
    image: influxdb:alpine
    ports:
      - "8083:8083"
      - "8086:8086"

  telegraf:
    image: luafran/telegraf:alpine
    ports:
      - "8125:8125/udp"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
