version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis-master
      - redis-slave
  redis-master:
    image: gcr.io/google_containers/redis:e2e
  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
