apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  type: NodePort
  ports:
  - port: 8125
    targetPort: 8125
    protocol: UDP
  selector:
    app: telegraf
    tier: monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf
        tier: monitoring
    spec:
      containers:
      - name: telegraf
        image: luafran/telegraf:alpine
        ports:
        - containerPort: 8125
          protocol: UDP
