apiVersion: v1
kind: Service
metadata:
  name: pubtrans
  labels:
    app: pubtrans
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: pubtrans
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubtrans
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pubtrans
        tier: frontend
    spec:
      containers:
      - name: pubtrans
        image: luafran/pubtrans:0.0.5.0
        ports:
        - containerPort: 8888
