apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: NodePort
  ports:
  - name: http-api
    port: 8083
    targetPort: 8083
    protocol: TCP
  - name: admin-api
    port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: influxdb
    tier: monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
        tier: monitoring
    spec:
      containers:
      - name: influxdb
        image: influxdb:alpine
        ports:
        - name: http-api
          containerPort: 8083
          protocol: TCP
        - name: admin-api
          containerPort: 8086
          protocol: TCP
